---
test-name: 'HWTest' #FOlder organization (Tx can override in 'begin')

rx:
  rx-freq-mhz: 1250 #BB60 tuneing (Tx can override in 'begin')
  tx-freq-mhz: 625 #transmit freq, just for file naming (Tx can override in 'begin')
  serial: 24248018 #BB60D serial number
  ref-lvl-dbm: -20 #spike ScaleFactor
  decimation: 1
  if-bandwidth-hz: 27000000
  bb-api-lib: null

# they tell me the smallest length is 1 sample = 25 ns at decimation 1
snippet:
  wait:     {enabled: true, length-sec: 0.0005, interval-sec: 3} #during initial wait time (after 'begin')
  tx:       {enabled: true, length-sec: 0.005, interval-sec: 1} #during tx ('start_tx' -> 'end_tx')
  recovery: {enabled: true, length-sec: 0.0005, interval-sec: 2} #during recovery time ('end_tx' -> next 'start_tx'/'end')

server:
  host: '127.0.0.1' #127.0.0.1 = localhost, 0.0.0.0 = other machines
  port: 5050 #arbitrary

output:
  dir: 'results' #snippets go under results/<test>/<state>/, and csv log under results/<test>/

max-freq-mhz: 6000 #stay safe

# mock: false = real hardware, true = simulated BB60 w no hardware. Use trigger_mock_tx.py to test.
mock: false
debug-mode: false